# Generated by Django 3.2.8 on 2021-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JyrTable',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('box_id', models.TextField(blank=True, null=True)),
                ('machine_name', models.TextField(blank=True, null=True)),
                ('controller_system_status', models.TextField(blank=True, null=True)),
                ('controller_system_alarm', models.TextField(blank=True, null=True)),
                ('axes_spindle_speed_command', models.TextField(blank=True, null=True)),
                ('controller_path_feedrate_actual', models.TextField(blank=True, null=True)),
                ('controller_path_program_mainno', models.TextField(blank=True, null=True)),
                ('controller_time_power', models.TextField(blank=True, null=True)),
                ('controller_time_cutting', models.TextField(blank=True, null=True)),
                ('controller_time_operation', models.TextField(blank=True, null=True)),
                ('axes_spindle_speed_override', models.TextField(blank=True, db_column='axes_spindle_speed-override', null=True)),
                ('controller_path_feedrate_override', models.TextField(blank=True, null=True)),
                ('axes_spindle_speed_actual', models.TextField(blank=True, null=True)),
                ('controller_time_cycle', models.TextField(blank=True, null=True)),
                ('controller_path_feedrate_command', models.TextField(blank=True, null=True)),
                ('controller_path_axes_servo_names', models.TextField(blank=True, null=True)),
                ('tools_numbe_now', models.TextField(blank=True, null=True)),
                ('controller_part_total', models.TextField(blank=True, null=True)),
                ('controller_part_count', models.TextField(blank=True, null=True)),
                ('controller_part_require', models.TextField(blank=True, null=True)),
                ('controller_system_message', models.TextField(blank=True, null=True)),
                ('controller_system_mode', models.FloatField(blank=True, null=True)),
                ('controller_path_pos_absolute', models.TextField(blank=True, null=True)),
                ('controller_path_pos_relative', models.TextField(blank=True, null=True)),
                ('controller_path_pos_machine', models.TextField(blank=True, null=True)),
                ('controller_path_pos_distance', models.TextField(blank=True, null=True)),
                ('controller_path_program_block', models.TextField(blank=True, null=True)),
                ('controller_path_program_runno', models.TextField(blank=True, null=True)),
                ('controller_path_program_rowno', models.TextField(blank=True, null=True)),
                ('controller_path_axes_count_max', models.TextField(blank=True, null=True)),
                ('controller_path_axes_count_now', models.TextField(blank=True, null=True)),
                ('controller_path_axes_names', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jyr_table',
                'managed': False,
            },
        ),
    ]
