# Generated by Django 3.2.8 on 2022-01-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_jyrtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='check_nums',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fiex_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='good_production',
        ),
        migrations.RemoveField(
            model_name='post',
            name='need_production_capacity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='production_capacity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='work_no',
        ),
        migrations.AddField(
            model_name='post',
            name='activation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fixtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='part_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='machine_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
