# Generated by Django 3.2.8 on 2022-01-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220106_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state_array',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='state_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
