# Generated by Django 3.2.8 on 2022-01-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220106_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
