# Generated by Django 3.2.8 on 2022-01-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_post_starting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='starting_part_count',
            field=models.IntegerField(null=True),
        ),
    ]
